import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import theme from "@/theme/theme";
import { ThemeProvider } from "@mui/material/styles";
import Header from '@/components/Header'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme = {theme}>
      <body className={inter.className}>
        <Header/>
        {children}
      </body>
      </ThemeProvider>
    </html>
  );
}
